project(
    'Zeal-NativeEmulator',
    'c',
    version: '1.0',
    license: 'Apache-2.0',
    default_options: [
        'buildtype=debugoptimized',
        'c_std=c99',
        'warning_level=everything',
        'warning_level=2',
    ],
)


# Output binary
dependencies = []
OUTPUT_BIN = 'zeal-native'
if (host_machine.system() == 'emscripten')
    OUTPUT_BIN = 'zeal.elf'
endif

# Retrieve raylib_path option (set via command line or use system defaults)
raylib_path = get_option('raylib_path')
raylib_target_path = meson.get_external_property('raylib_path', '')

if raylib_path != ''
    # Target provided path
    raylib_include_dir = raylib_path / 'include'
    raylib_lib_dir = raylib_path / 'lib'
elif raylib_target_path != ''
    # Target provided path
    raylib_include_dir = raylib_target_path / 'include'
    raylib_lib_dir = raylib_target_path / 'lib'
else
    # No path provided, rely on system's default libraries (i.e., /usr/include and /usr/lib)
    raylib_include_dir = ''
    raylib_lib_dir = ''
endif


# List all the subdirectories that contain source code
sources = []
subdir('hw')
subdir('utils')
subdir('assets')

run_command('mkdir', '-p', join_paths(meson.project_build_root(), 'roms'), check: true)
res = run_command(
    'cp',
    'roms/default.img',
    join_paths(meson.project_build_root(), 'roms/default.img'),
    check: false,
)

if res.returncode() != 0
  warning('default.img not found, skipping copy')
endif

add_project_arguments('-DZEAL_NATIVE', language: 'c')
if (get_option('show_fps'))
    add_project_arguments('-DCONFIG_SHOW_FPS', language: 'c')
endif

if get_option('enable_debugger')
    add_project_arguments('-DCONFIG_ENABLE_DEBUGGER', language: 'c')
endif

if (host_machine.system() == 'darwin')
    add_project_arguments('-D_DARWIN_C_SOURCE', language: 'c')
endif

add_project_arguments('-D_XOPEN_SOURCE=700',
                      '-Iinclude',
                      language: 'c')

if raylib_include_dir != ''
    add_project_arguments('-I' + raylib_include_dir, language: 'c')
endif

if raylib_lib_dir != ''
    add_project_link_arguments('-L' + raylib_lib_dir, language: 'c')
endif

add_project_link_arguments('-lraylib', '-lm', language: 'c')

linker_args = meson.get_external_property('link_args', [])

# Compiler and build targets
exec = executable(
    OUTPUT_BIN,
    sources,
    include_directories: ['include'],
    dependencies: dependencies,
    link_args: linker_args,
    install: true
)

# meson compile run to launch emulator after building
run_target(
    'run',
    command: [exec],
)

# We have to do it here so that the final file is at the root of the build dir
if (host_machine.system() == 'emscripten')
    wasm_template = get_option('wasm_template')
    wasm_dir = join_paths(meson.project_source_root(), 'assets', 'wasm', wasm_template)
    configure_file(
        input: join_paths(wasm_dir, 'index.html'),
        output: 'index.html',
        copy: true
    )
    if(wasm_template == 'minimal')
        configure_file(
            input: join_paths(wasm_dir, 'index.js'),
            output: 'index.js',
            copy: true
        )
    endif
    configure_file(
        input: join_paths(wasm_dir, 'index.css'),
        output: 'index.css',
        copy: true
    )

    patch_script = join_paths(meson.project_source_root(), 'tools', 'wasm_patch.py')

    patch_wasm = custom_target('patch_wasm',
        output: 'dummy_file',
        command: ['python3', patch_script, OUTPUT_BIN + '.js'],
        depends: exec,
        build_by_default: true,
    )
endif

